# Generated by Django 3.1.3 on 2020-11-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='email_of_company',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='CamerasInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_camera', models.CharField(max_length=30)),
                ('ip_of_camera', models.CharField(max_length=50)),
                ('number_of_camera', models.IntegerField(default=0)),
                ('is_running', models.BooleanField()),
                ('company_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.companyinfo')),
            ],
        ),
    ]
