# Generated by Django 3.1.3 on 2020-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201115_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerasinfo',
            name='number_of_camera',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='number_of_camera',
            field=models.IntegerField(default=0),
        ),
    ]
